### ISSUE TITLE
Overhaul validation procedure (conceptionally and technically)

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#21]

**Comment by ghost** [comment]
- [x] Validation described as process and result of the comparison of the original analysis on the one hand and the reproduced analysis on the other hand.

- [x] Critically examined the terminology around _comparison_, _validation_ and _analysis_ in order to find a precise description of the process that is in accord with the reference tool suite (e.g. _comparer_)

- [x] Distinguished _validation_ of the ERC (the result; the reproduced analysis) from _bag validation_ in terms of BagIt Bags

**Comment by nuest** [comment]
On our (old...) poster we use the terms "check metadata" and "check execution" (which means "compare the execution results to reference results").

Maybe we can use the terms _bag validation_ (still never use the word validation without bag) and _ERC check_ or _check of ERC_. The latter comprises a metadata check, an execution check (the inner container runs), and a result check (= comparison against reference workspace).

The word "validation" might also be too strong for us to use anyway. We can "check the result of computations in a controlled environment", but a replication study (different data/code etc.) can validate the results.

**Comment by ghost** [comment]
This sounds reasonable to me and seems to be handy wording.

**Comment by ghost** [comment]
Results of our discussion:
https://github.com/o2r-project/erc-spec/issues/35
