### ISSUE TITLE
 Render PDF with GH action

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#77]
Remove usage of Travis CI

**Comment by Fmazin** [comment]
I have unfortunately a roadblock with this action. This due to two problems:

1. The most reliable way to use pandoc in an action is through its docker container. However this container does not find the pandoc-latex-admonition. Without the filter the pdf can be generated. 
2. The generated name for the output PDF file seems to be unable to be read. 

For more detailed infos see my fork: https://github.com/Fmazin/erc-spec/actions#

**Comment by Fmazin** [comment]
The roadblocks have been resolved a PR will follow soon.
