### ISSUE TITLE
Add single file HTML and MD output of spec and store it in each ERC

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#9]
use https://github.com/jgrassler/mkdocs-pandoc to create single file, then https://github.com/jgrassler/mkdocs-pandoc#usage-example and http://pandoc.org/demos.html to create

- [x] single Markdown document output of spec is part of Travis build @nuest 
- [x] the version of the spec is available at http://o2r.info/erc-spec/erc-spec-v1.md @nuest
- [x] new content for spec where in the ERC the actual spec is stored (integrate with `spec_version`!) > #10 
- [x] Automatically download (see URL above) and (a) save the latest spec version into ERC during creation in _extractor_ and (b) creates a file `.erc/erc_raw.yml` @7048730 
- [x] PDF is at http://o2r.info/erc-spec/erc-spec-v1.md
- [x] unversioned PDF and single file markdown at http://o2r.info/erc-spec/erc-spec.pdf respectively http://o2r.info/erc-spec/erc-spec.md

**Comment by nuest** [comment]
@7048730 should we store the spec within the ERC as a PDF or as an HTML file?

**Comment by ghost** [comment]
how about PDF/A for long term preservation and additionally markdown for usability?

**Comment by nuest** [comment]
PDF/A with pandoc... that could be a challenge :-). I didn't find anything in that direction, so any pointers are helpful.

_An what about the file names and paths?_

**Comment by ghost** [comment]
cf. https://github.com/jgm/pandoc/issues/3215

Since PDF/A seems problematic, I'd go for a text version that is as much plain text as possible. On the other hand, as we do use a lot of hyperlinks, we might be okay using markdown anyway, which is after all only very lightwightedly encoded and thus easy to preserve.

As for the filenames and paths, it might be reasonable from a preservationist's point of view to include the different spec outputs in directories that label them, e.g. `erc/spec/markdown/spec.md` and so on. At a point, one could add addtional information on the formats used here within that dir.

**Comment by nuest** [comment]
No PDF/A for us, paths to the plain text documents are listed in the archival metadata, see #10
